import { type Metadata } from "next";
import {ClerkProvider} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <SidebarProvider >
      <html lang="en" suppressHydrationWarning={true}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
           attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
          <main className="grid grid-cols-1 lg:grid-cols-8">
            <aside className="col-span-2">
                <AppSidebar />
            </aside>
            <section className="col-span-5 p-8">
              <SidebarTrigger />
              {children}
              </section>
          </main>
          </ThemeProvider>
        </body>
      </html>
              </SidebarProvider>
    </ClerkProvider>
  );
}
